name: RESTAPI
channels: 
  - anaconda
  - conda-forge
  - defaults
  # - pytorch
dependencies:
  - python=3.7
  - pip=20.2.4
  - pip:
    - fastapi==0.63.0
    - numpy==1.18.5
    - pandas==1.1.3
    - scikit-learn==0.23.2
    - ipykernel
    - jupyter==1.0.0
    # - tqdm==4.46.1
    - matplotlib==3.3.3
    # - seaborn==0.10.1
    # - tensorflow==2.4.0
    # - keras==2.4.3
    - opencv-python==4.5.1.48
    # - cmake==3.18.4
    # - dlib==19.21.1
    - pillow==5.4.1
    - plotly==3.7.0
    - boto3==1.17.12
    # - moviepy==1.0.3
    # - Path==15.1.2
    - httpx==0.17.1